import { StyleSheet } from 'react-native';

export const habitStyles = StyleSheet.create({
  habitHeader: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  habitHeaderText: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1F2937',
  },
  daterange: {
    marginTop: 4,
    fontSize: 14,
    color: '#6B7280',
  },
  progress: {
    marginTop: 6,
    fontSize: 14,
    color: '#374151',
  },
  addHabitButton: {
    position: 'absolute',
    right: 16,
    top: 18,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#E5F4EE', 
  },
  addHabitButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#065F46',
  },
  dailyHeader: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  dailyHeaderText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  weeklyHeader: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  weeklyHeaderText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  habitInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
  },
  dayHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 6,
    gap: 12,
  },
  dayHeaderText: {
    width: 18,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
  },
  habitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  habitName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginRight: 10,
  },
  dayBoxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dayBox: {
    width: 18,
    height: 18,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
  },
  dayBoxChecked: {
    backgroundColor: '#10B981',
    borderColor: '#10B981',
  },
  weeklyBox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
  },
  weeklyBoxChecked: {
    backgroundColor: '#10B981',
    borderColor: '#10B981',
  },
  emptyText: {
    paddingVertical: 16,
    textAlign: 'center',
    fontSize: 14,
    color: '#9CA3AF',
  },
  frequencyLabel: {
  marginTop: 6,
  marginBottom: 8,
  fontSize: 14,
  fontWeight: '600',
  color: '#374151',
},
frequencyRow: {
  flexDirection: 'row',
  gap: 10,
},
frequencyButton: {
  paddingVertical: 8,
  paddingHorizontal: 12,
  borderRadius: 18,
  borderWidth: 1,
  borderColor: '#D1D5DB',
  backgroundColor: '#FFFFFF',
},
frequencySelected: {
  borderColor: '#10B981',
  backgroundColor: '#E5F4EE',
},
frequencyButtonText: {
  fontSize: 14,
  fontWeight: '600',
  color: '#374151',
},
frequencySelectedText: {
  color: '#065F46',
},
});
